// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/app/viewunite/v1/airelate.proto" (package "bilibili.app.viewunite.v1", syntax proto3)
// tslint:disable
import { MessageType, reflectionMergePartial, UnknownFieldHandler, WireType } from "@protobuf-ts/runtime";
import { CM } from "./viewunite.js";

// @generated message type with reflection information, may provide speed optimized methods
class AIRelateCards$Type extends MessageType {
	constructor() {
		super("bilibili.app.viewunite.v1.AIRelateCards", [{ no: 1, name: "cards", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 12 /*ScalarType.BYTES*/ }]);
	}
	create(value) {
		const message = globalThis.Object.create(this.messagePrototype);
		message.cards = [];
		if (value !== undefined) reflectionMergePartial(this, message, value);
		return message;
	}
	internalBinaryRead(reader, length, options, target) {
		const message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			const [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* repeated bytes cards */ 1:
					message.cards.push(reader.bytes());
					break;
				default: {
					const u = options.readUnknownField;
					if (u === "throw") throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
					const d = reader.skip(wireType);
					if (u !== false) (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
				}
			}
		}
		return message;
	}
	internalBinaryWrite(message, writer, options) {
		/* repeated bytes cards = 1; */
		for (const card of message.cards) writer.tag(1, WireType.LengthDelimited).bytes(card);
		const u = options.writeUnknownFields;
		if (u !== false) (u === true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.AIRelateCards
 */
export const AIRelateCards = new AIRelateCards$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AIRelateModule$Type extends MessageType {
	constructor() {
		super("bilibili.app.viewunite.v1.AIRelateModule", [
			{ no: 1, name: "type", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
			{ no: 22, name: "relates", kind: "message", T: () => AIRelateCards },
		]);
	}
	create(value) {
		const message = globalThis.Object.create(this.messagePrototype);
		message.type = 0;
		if (value !== undefined) reflectionMergePartial(this, message, value);
		return message;
	}
	internalBinaryRead(reader, length, options, target) {
		const message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			const [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* int32 type */ 1:
					message.type = reader.int32();
					break;
				case /* bilibili.app.viewunite.v1.AIRelateCards relates */ 22:
					message.relates = AIRelateCards.internalBinaryRead(reader, reader.uint32(), options, message.relates);
					break;
				default: {
					const u = options.readUnknownField;
					if (u === "throw") throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
					const d = reader.skip(wireType);
					if (u !== false) (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
				}
			}
		}
		return message;
	}
	internalBinaryWrite(message, writer, options) {
		/* int32 type = 1; */
		if (message.type !== 0) writer.tag(1, WireType.Varint).int32(message.type);
		/* bilibili.app.viewunite.v1.AIRelateCards relates = 22; */
		if (message.relates) AIRelateCards.internalBinaryWrite(message.relates, writer.tag(22, WireType.LengthDelimited).fork(), options).join();
		const u = options.writeUnknownFields;
		if (u !== false) (u === true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.AIRelateModule
 */
export const AIRelateModule = new AIRelateModule$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AIRelateTab$Type extends MessageType {
	constructor() {
		super("bilibili.app.viewunite.v1.AIRelateTab", [{ no: 1, name: "modules", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => AIRelateModule }]);
	}
	create(value) {
		const message = globalThis.Object.create(this.messagePrototype);
		message.modules = [];
		if (value !== undefined) reflectionMergePartial(this, message, value);
		return message;
	}
	internalBinaryRead(reader, length, options, target) {
		const message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			const [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* repeated bilibili.app.viewunite.v1.AIRelateModule modules */ 1:
					message.modules.push(AIRelateModule.internalBinaryRead(reader, reader.uint32(), options));
					break;
				default: {
					const u = options.readUnknownField;
					if (u === "throw") throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
					const d = reader.skip(wireType);
					if (u !== false) (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
				}
			}
		}
		return message;
	}
	internalBinaryWrite(message, writer, options) {
		/* repeated bilibili.app.viewunite.v1.AIRelateModule modules = 1; */
		for (const module of message.modules) AIRelateModule.internalBinaryWrite(module, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
		const u = options.writeUnknownFields;
		if (u !== false) (u === true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.AIRelateTab
 */
export const AIRelateTab = new AIRelateTab$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AIRelateReply$Type extends MessageType {
	constructor() {
		super("bilibili.app.viewunite.v1.AIRelateReply", [
			{ no: 1, name: "cm", kind: "message", T: () => CM },
			{ no: 2, name: "tab", kind: "message", T: () => AIRelateTab },
		]);
	}
	create(value) {
		const message = globalThis.Object.create(this.messagePrototype);
		if (value !== undefined) reflectionMergePartial(this, message, value);
		return message;
	}
	internalBinaryRead(reader, length, options, target) {
		const message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			const [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* bilibili.app.viewunite.v1.CM cm */ 1:
					message.cm = CM.internalBinaryRead(reader, reader.uint32(), options, message.cm);
					break;
				case /* bilibili.app.viewunite.v1.AIRelateTab tab */ 2:
					message.tab = AIRelateTab.internalBinaryRead(reader, reader.uint32(), options, message.tab);
					break;
				default: {
					const u = options.readUnknownField;
					if (u === "throw") throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
					const d = reader.skip(wireType);
					if (u !== false) (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
				}
			}
		}
		return message;
	}
	internalBinaryWrite(message, writer, options) {
		/* bilibili.app.viewunite.v1.CM cm = 1; */
		if (message.cm) CM.internalBinaryWrite(message.cm, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
		/* bilibili.app.viewunite.v1.AIRelateTab tab = 2; */
		if (message.tab) AIRelateTab.internalBinaryWrite(message.tab, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
		const u = options.writeUnknownFields;
		if (u !== false) (u === true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.AIRelateReply
 */
export const AIRelateReply = new AIRelateReply$Type();
