// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/app/viewunite/v1/airelate.proto" (package "bilibili.app.viewunite.v1", syntax proto3)
// tslint:disable
import { MessageType, reflectionMergePartial, UnknownFieldHandler, WireType } from "@protobuf-ts/runtime";
import { CM } from "./viewunite.js";

// @generated message type with reflection information, may provide speed optimized methods
class AIRelateReply$Type extends MessageType {
	constructor() {
		super("bilibili.app.viewunite.v1.AIRelateReply", [{ no: 1, name: "cm", kind: "message", T: () => CM }]);
	}
	create(value) {
		const message = globalThis.Object.create(this.messagePrototype);
		if (value !== undefined) reflectionMergePartial(this, message, value);
		return message;
	}
	internalBinaryRead(reader, length, options, target) {
		const message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			const [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* bilibili.app.viewunite.v1.CM cm */ 1:
					message.cm = CM.internalBinaryRead(reader, reader.uint32(), options, message.cm);
					break;
				default: {
					const u = options.readUnknownField;
					if (u === "throw") throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
					const d = reader.skip(wireType);
					if (u !== false) (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
				}
			}
		}
		return message;
	}
	internalBinaryWrite(message, writer, options) {
		/* bilibili.app.viewunite.v1.CM cm = 1; */
		if (message.cm) CM.internalBinaryWrite(message.cm, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
		const u = options.writeUnknownFields;
		if (u !== false) (u === true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.AIRelateReply
 */
export const AIRelateReply = new AIRelateReply$Type();
