// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/app/viewunite/v1/airelate.proto" (package "bilibili.app.viewunite.v1", syntax proto3)
// tslint:disable
import type { BinaryReadOptions, BinaryWriteOptions, IBinaryReader, IBinaryWriter, PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { CM } from "./viewunite.js";
/**
 * Wire-compatible subset of the AIRelateAsync response. Leave recommendations
 * and other fields undeclared so the runtime preserves their original bytes.
 *
 * @generated from protobuf message bilibili.app.viewunite.v1.AIRelateReply
 */
export interface AIRelateReply {
	/**
	 * @generated from protobuf field: bilibili.app.viewunite.v1.CM cm = 1
	 */
	cm?: CM;
}
declare class AIRelateReply$Type extends MessageType<AIRelateReply> {
	constructor();
	create(value?: PartialMessage<AIRelateReply>): AIRelateReply;
	internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AIRelateReply): AIRelateReply;
	internalBinaryWrite(message: AIRelateReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.AIRelateReply
 */
export declare const AIRelateReply: AIRelateReply$Type;
