// @generated by protobuf-ts 2.11.1 with parameter long_type_string,output_javascript
// @generated from protobuf file "bilibili/app/viewunite/v1/airelate.proto" (package "bilibili.app.viewunite.v1", syntax proto3)
// tslint:disable
import type { BinaryReadOptions, BinaryWriteOptions, IBinaryReader, IBinaryWriter, PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { CM } from "./viewunite.js";
/**
 * Wire-compatible subset of the AIRelateAsync response. Keep card payloads as
 * bytes so filtering does not reserialize the recommendations that remain.
 *
 * @generated from protobuf message bilibili.app.viewunite.v1.AIRelateCards
 */
export interface AIRelateCards {
	/**
	 * @generated from protobuf field: repeated bytes cards = 1
	 */
	cards: Uint8Array[];
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.AIRelateModule
 */
export interface AIRelateModule {
	/**
	 * @generated from protobuf field: int32 type = 1
	 */
	type: number;
	/**
	 * @generated from protobuf field: bilibili.app.viewunite.v1.AIRelateCards relates = 22
	 */
	relates?: AIRelateCards;
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.AIRelateTab
 */
export interface AIRelateTab {
	/**
	 * @generated from protobuf field: repeated bilibili.app.viewunite.v1.AIRelateModule modules = 1
	 */
	modules: AIRelateModule[];
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.AIRelateReply
 */
export interface AIRelateReply {
	/**
	 * @generated from protobuf field: bilibili.app.viewunite.v1.CM cm = 1
	 */
	cm?: CM;
	/**
	 * @generated from protobuf field: bilibili.app.viewunite.v1.AIRelateTab tab = 2
	 */
	tab?: AIRelateTab;
}
declare class AIRelateCards$Type extends MessageType<AIRelateCards> {
	constructor();
	create(value?: PartialMessage<AIRelateCards>): AIRelateCards;
	internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AIRelateCards): AIRelateCards;
	internalBinaryWrite(message: AIRelateCards, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.AIRelateCards
 */
export declare const AIRelateCards: AIRelateCards$Type;
declare class AIRelateModule$Type extends MessageType<AIRelateModule> {
	constructor();
	create(value?: PartialMessage<AIRelateModule>): AIRelateModule;
	internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AIRelateModule): AIRelateModule;
	internalBinaryWrite(message: AIRelateModule, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.AIRelateModule
 */
export declare const AIRelateModule: AIRelateModule$Type;
declare class AIRelateTab$Type extends MessageType<AIRelateTab> {
	constructor();
	create(value?: PartialMessage<AIRelateTab>): AIRelateTab;
	internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AIRelateTab): AIRelateTab;
	internalBinaryWrite(message: AIRelateTab, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.AIRelateTab
 */
export declare const AIRelateTab: AIRelateTab$Type;
declare class AIRelateReply$Type extends MessageType<AIRelateReply> {
	constructor();
	create(value?: PartialMessage<AIRelateReply>): AIRelateReply;
	internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AIRelateReply): AIRelateReply;
	internalBinaryWrite(message: AIRelateReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.AIRelateReply
 */
export declare const AIRelateReply: AIRelateReply$Type;
